//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBO_Open.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Speler()
        {
            this.Aanmeldingens = new HashSet<Aanmeldingen>();
            this.Wedstrijdens = new HashSet<Wedstrijden>();
            this.Wedstrijdens1 = new HashSet<Wedstrijden>();
            this.Wedstrijdens2 = new HashSet<Wedstrijden>();
        }
    
        public int ID { get; set; }
        public string Voornaam { get; set; }
        public string Tussenvoegsels { get; set; }
        public string Achternaam { get; set; }
        public int SchoolID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aanmeldingen> Aanmeldingens { get; set; }
        public virtual Scholen Scholen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wedstrijden> Wedstrijdens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wedstrijden> Wedstrijdens1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wedstrijden> Wedstrijdens2 { get; set; }
    }
}
