//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBO_Open.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wedstrijden
    {
        public int ID { get; set; }
        public int ToernooiID { get; set; }
        public short Ronde { get; set; }
        public int Speler1ID { get; set; }
        public Nullable<int> Speler2ID { get; set; }
        public Nullable<int> Score1 { get; set; }
        public Nullable<int> Score2 { get; set; }
        public Nullable<int> WinnaarID { get; set; }
    
        public virtual Speler Speler { get; set; }
        public virtual Speler Speler1 { get; set; }
        public virtual Speler Speler2 { get; set; }
        public virtual Toernooien Toernooien { get; set; }
    }
}
